name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Ensure all your requirements are listed in requirements.txt
        pip install -r requirements.txt
        pip install selenium pytest-asyncio pytest requests aiohttp

    - name: Verify config directory exists
      run: |
        mkdir -p my_digital_being/config

    - name: Run tests
      env:
        COMPOSIO_API_KEY: ${{ secrets.COMPOSIO_API_KEY }}
      run: |
        pytest tests/ 