name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure all your requirements are listed in requirements.txt
          # Example (installing manually):
          pip install -r requirements.txt
          pip install selenium pytest-asyncio pytest requests aiohttp

      # 4. Setup Config Directory
      - name: Setup Config Directory
        run: |
          mkdir -p my_digital_being/config

      # 5. Install Chrome and Chromedriver
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Remove or replace existing chromedriver symlink, if any
          if [ -L /usr/bin/chromedriver ]; then
            sudo rm /usr/bin/chromedriver
          elif [ -e /usr/bin/chromedriver ]; then
            sudo rm /usr/bin/chromedriver
          fi
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      # 6. Run Tests
      - name: Run Tests
        env:
          COMPOSIO_API_KEY: ${{ secrets.COMPOSIO_API_KEY }}
        run: |
          pytest tests/ --maxfail=5 --disable-warnings
